void test_numeric_char_common_1();
void test_numeric_char_put_1();
void test_numeric_char_put_2();
void test_numeric_char_put_3();
void test_numeric_char_put_4();
void test_numeric_char_put_5();
void test_numeric_char_put_6();
void test_numeric_char_put_7();
void test_numeric_char_put_8();
void test_numeric_char_put_9();
void test_numeric_char_put_10();
void test_numeric_char_put_11();
void test_numeric_char_put_12();
void test_numeric_char_put_13();
void test_numeric_char_put_14();
void test_numeric_char_put_15();
void test_numeric_char_put_16();
void test_numeric_char_put_17();
void test_numeric_char_put_18();
void test_numeric_char_get_1();
void test_numeric_char_get_2();
void test_numeric_char_get_3();
void test_numeric_char_get_4();
void test_numeric_char_get_5();
void test_numeric_char_get_6();
void test_numeric_char_get_7();
void test_numeric_char_get_8();
void test_numeric_char_get_9();
void test_numeric_char_get_10();
void test_numeric_char_get_11();
void test_numeric_char_get_12();
void test_numeric_char_get_13();
void test_numeric_char_get_14();
void test_numeric_char_get_15();
void test_numeric_char_get_16();
void test_numeric_char_get_17();
void test_numeric_char_get_18();
void test_numeric_char_get_19();
void test_numeric_char_get_20();
void test_numeric_char_get_21();
void test_numeric_char_get_22();
void test_numeric_char_get_23();
void test_numeric_char_get_24();
void test_numeric_char_get_25();
void test_numeric_char_get_26();
void test_numeric_char_get_27();
void test_numeric_char_get_28();
void test_numeric_char_get_29();
void test_numeric_char_get_30();
void test_numeric_char_get_31();
void test_numeric_char_get_32();
void test_numeric_char_get_33();
void test_numeric_char_get_34();
void test_numeric_char_get_35();
void test_numeric_char_get_36();
void test_numeric_char_get_37();
void test_numeric_char_get_38();
void test_numeric_char_get_39();
void test_numeric_char_get_40();
void test_numeric_char_get_41();
void test_numeric_char_get_42();

void test_numeric_wchar_t_common_1();
void test_numeric_wchar_t_put_1();
void test_numeric_wchar_t_put_2();
void test_numeric_wchar_t_put_3();
void test_numeric_wchar_t_put_4();
void test_numeric_wchar_t_put_5();
void test_numeric_wchar_t_put_6();
void test_numeric_wchar_t_put_7();
void test_numeric_wchar_t_put_8();
void test_numeric_wchar_t_put_9();
void test_numeric_wchar_t_put_10();
void test_numeric_wchar_t_put_11();
void test_numeric_wchar_t_put_12();
void test_numeric_wchar_t_put_13();
void test_numeric_wchar_t_put_14();
void test_numeric_wchar_t_put_15();
void test_numeric_wchar_t_put_16();
void test_numeric_wchar_t_put_17();
void test_numeric_wchar_t_put_18();
void test_numeric_wchar_t_get_1();
void test_numeric_wchar_t_get_2();
void test_numeric_wchar_t_get_3();
void test_numeric_wchar_t_get_4();
void test_numeric_wchar_t_get_5();
void test_numeric_wchar_t_get_6();
void test_numeric_wchar_t_get_7();
void test_numeric_wchar_t_get_8();
void test_numeric_wchar_t_get_9();
void test_numeric_wchar_t_get_10();
void test_numeric_wchar_t_get_11();
void test_numeric_wchar_t_get_12();
void test_numeric_wchar_t_get_13();
void test_numeric_wchar_t_get_14();
void test_numeric_wchar_t_get_15();
void test_numeric_wchar_t_get_16();
void test_numeric_wchar_t_get_17();
void test_numeric_wchar_t_get_18();
void test_numeric_wchar_t_get_19();
void test_numeric_wchar_t_get_20();
void test_numeric_wchar_t_get_21();

void test_numeric_char32_t_common_1();
void test_numeric_char32_t_put_1();
void test_numeric_char32_t_put_2();
void test_numeric_char32_t_put_3();
void test_numeric_char32_t_put_4();
void test_numeric_char32_t_put_5();
void test_numeric_char32_t_put_6();
void test_numeric_char32_t_put_7();
void test_numeric_char32_t_put_8();
void test_numeric_char32_t_put_9();
void test_numeric_char32_t_put_10();
void test_numeric_char32_t_put_11();
void test_numeric_char32_t_put_12();
void test_numeric_char32_t_put_13();
void test_numeric_char32_t_put_14();
void test_numeric_char32_t_put_15();
void test_numeric_char32_t_put_16();
void test_numeric_char32_t_put_17();
void test_numeric_char32_t_put_18();
void test_numeric_char32_t_get_1();
void test_numeric_char32_t_get_2();
void test_numeric_char32_t_get_3();
void test_numeric_char32_t_get_4();
void test_numeric_char32_t_get_5();
void test_numeric_char32_t_get_6();
void test_numeric_char32_t_get_7();
void test_numeric_char32_t_get_8();
void test_numeric_char32_t_get_9();
void test_numeric_char32_t_get_10();
void test_numeric_char32_t_get_11();
void test_numeric_char32_t_get_12();
void test_numeric_char32_t_get_13();
void test_numeric_char32_t_get_14();
void test_numeric_char32_t_get_15();
void test_numeric_char32_t_get_16();
void test_numeric_char32_t_get_17();
void test_numeric_char32_t_get_18();
void test_numeric_char32_t_get_19();
void test_numeric_char32_t_get_20();
void test_numeric_char32_t_get_21();

void test_numeric_char8_t_common_1();
void test_numeric_char8_t_put_1();
void test_numeric_char8_t_put_2();
void test_numeric_char8_t_put_3();
void test_numeric_char8_t_put_4();
void test_numeric_char8_t_put_5();
void test_numeric_char8_t_put_6();
void test_numeric_char8_t_put_7();
void test_numeric_char8_t_put_8();
void test_numeric_char8_t_put_9();
void test_numeric_char8_t_put_10();
void test_numeric_char8_t_put_11();
void test_numeric_char8_t_put_12();
void test_numeric_char8_t_put_13();
void test_numeric_char8_t_put_14();
void test_numeric_char8_t_put_15();
void test_numeric_char8_t_put_16();
void test_numeric_char8_t_put_17();
void test_numeric_char8_t_put_18();
void test_numeric_char8_t_get_1();
void test_numeric_char8_t_get_2();
void test_numeric_char8_t_get_3();
void test_numeric_char8_t_get_4();
void test_numeric_char8_t_get_5();
void test_numeric_char8_t_get_6();
void test_numeric_char8_t_get_7();
void test_numeric_char8_t_get_8();
void test_numeric_char8_t_get_9();
void test_numeric_char8_t_get_10();
void test_numeric_char8_t_get_11();
void test_numeric_char8_t_get_12();
void test_numeric_char8_t_get_13();
void test_numeric_char8_t_get_14();
void test_numeric_char8_t_get_15();
void test_numeric_char8_t_get_16();
void test_numeric_char8_t_get_17();
void test_numeric_char8_t_get_18();
void test_numeric_char8_t_get_19();
void test_numeric_char8_t_get_20();
void test_numeric_char8_t_get_21();

void test_numeric()
{
    test_numeric_char_common_1();
    test_numeric_char_put_1();
    test_numeric_char_put_2();
    test_numeric_char_put_3();
    test_numeric_char_put_4();
    test_numeric_char_put_5();
    test_numeric_char_put_6();
    test_numeric_char_put_7();
    test_numeric_char_put_8();
    test_numeric_char_put_9();
    test_numeric_char_put_10();
    test_numeric_char_put_11();
    test_numeric_char_put_12();
    test_numeric_char_put_13();
    test_numeric_char_put_14();
    test_numeric_char_put_15();
    test_numeric_char_put_16();
    test_numeric_char_put_17();
    test_numeric_char_put_18();
    test_numeric_char_get_1();
    test_numeric_char_get_2();
    test_numeric_char_get_3();
    test_numeric_char_get_4();
    test_numeric_char_get_5();
    test_numeric_char_get_6();
    test_numeric_char_get_7();
    test_numeric_char_get_8();
    test_numeric_char_get_9();
    test_numeric_char_get_10();
    test_numeric_char_get_11();
    test_numeric_char_get_12();
    test_numeric_char_get_13();
    test_numeric_char_get_14();
    test_numeric_char_get_15();
    test_numeric_char_get_16();
    test_numeric_char_get_17();
    test_numeric_char_get_18();
    test_numeric_char_get_19();
    test_numeric_char_get_20();
    test_numeric_char_get_21();
    test_numeric_char_get_22();
    test_numeric_char_get_23();
    test_numeric_char_get_24();
    test_numeric_char_get_25();
    test_numeric_char_get_26();
    test_numeric_char_get_27();
    test_numeric_char_get_28();
    test_numeric_char_get_29();
    test_numeric_char_get_30();
    test_numeric_char_get_31();
    test_numeric_char_get_32();
    test_numeric_char_get_33();
    test_numeric_char_get_34();
    test_numeric_char_get_35();
    test_numeric_char_get_36();
    test_numeric_char_get_37();
    test_numeric_char_get_38();
    test_numeric_char_get_39();
    test_numeric_char_get_40();
    test_numeric_char_get_41();
    test_numeric_char_get_42();

    test_numeric_wchar_t_common_1();
    test_numeric_wchar_t_put_1();
    test_numeric_wchar_t_put_2();
    test_numeric_wchar_t_put_3();
    test_numeric_wchar_t_put_4();
    test_numeric_wchar_t_put_5();
    test_numeric_wchar_t_put_6();
    test_numeric_wchar_t_put_7();
    test_numeric_wchar_t_put_8();
    test_numeric_wchar_t_put_9();
    test_numeric_wchar_t_put_10();
    test_numeric_wchar_t_put_11();
    test_numeric_wchar_t_put_12();
    test_numeric_wchar_t_put_13();
    test_numeric_wchar_t_put_14();
    test_numeric_wchar_t_put_15();
    test_numeric_wchar_t_put_16();
    test_numeric_wchar_t_put_17();
    test_numeric_wchar_t_put_18();
    test_numeric_wchar_t_get_1();
    test_numeric_wchar_t_get_2();
    test_numeric_wchar_t_get_3();
    test_numeric_wchar_t_get_4();
    test_numeric_wchar_t_get_5();
    test_numeric_wchar_t_get_6();
    test_numeric_wchar_t_get_7();
    test_numeric_wchar_t_get_8();
    test_numeric_wchar_t_get_9();
    test_numeric_wchar_t_get_10();
    test_numeric_wchar_t_get_11();
    test_numeric_wchar_t_get_12();
    test_numeric_wchar_t_get_13();
    test_numeric_wchar_t_get_14();
    test_numeric_wchar_t_get_15();
    test_numeric_wchar_t_get_16();
    test_numeric_wchar_t_get_17();
    test_numeric_wchar_t_get_18();
    test_numeric_wchar_t_get_19();
    test_numeric_wchar_t_get_20();
    test_numeric_wchar_t_get_21();
    
    test_numeric_char32_t_common_1();
    test_numeric_char32_t_put_1();
    test_numeric_char32_t_put_2();
    test_numeric_char32_t_put_3();
    test_numeric_char32_t_put_4();
    test_numeric_char32_t_put_5();
    test_numeric_char32_t_put_6();
    test_numeric_char32_t_put_7();
    test_numeric_char32_t_put_8();
    test_numeric_char32_t_put_9();
    test_numeric_char32_t_put_10();
    test_numeric_char32_t_put_11();
    test_numeric_char32_t_put_12();
    test_numeric_char32_t_put_13();
    test_numeric_char32_t_put_14();
    test_numeric_char32_t_put_15();
    test_numeric_char32_t_put_16();
    test_numeric_char32_t_put_17();
    test_numeric_char32_t_put_18();
    test_numeric_char32_t_get_1();
    test_numeric_char32_t_get_2();
    test_numeric_char32_t_get_3();
    test_numeric_char32_t_get_4();
    test_numeric_char32_t_get_5();
    test_numeric_char32_t_get_6();
    test_numeric_char32_t_get_7();
    test_numeric_char32_t_get_8();
    test_numeric_char32_t_get_9();
    test_numeric_char32_t_get_10();
    test_numeric_char32_t_get_11();
    test_numeric_char32_t_get_12();
    test_numeric_char32_t_get_13();
    test_numeric_char32_t_get_14();
    test_numeric_char32_t_get_15();
    test_numeric_char32_t_get_16();
    test_numeric_char32_t_get_17();
    test_numeric_char32_t_get_18();
    test_numeric_char32_t_get_19();
    test_numeric_char32_t_get_20();
    test_numeric_char32_t_get_21();
    
    test_numeric_char8_t_common_1();
    test_numeric_char8_t_put_1();
    test_numeric_char8_t_put_2();
    test_numeric_char8_t_put_3();
    test_numeric_char8_t_put_4();
    test_numeric_char8_t_put_5();
    test_numeric_char8_t_put_6();
    test_numeric_char8_t_put_7();
    test_numeric_char8_t_put_8();
    test_numeric_char8_t_put_9();
    test_numeric_char8_t_put_10();
    test_numeric_char8_t_put_11();
    test_numeric_char8_t_put_12();
    test_numeric_char8_t_put_13();
    test_numeric_char8_t_put_14();
    test_numeric_char8_t_put_15();
    test_numeric_char8_t_put_16();
    test_numeric_char8_t_put_17();
    test_numeric_char8_t_get_1();
    test_numeric_char8_t_get_2();
    test_numeric_char8_t_get_3();
    test_numeric_char8_t_get_4();
    test_numeric_char8_t_get_5();
    test_numeric_char8_t_get_6();
    test_numeric_char8_t_get_7();
    test_numeric_char8_t_get_8();
    test_numeric_char8_t_get_9();
    test_numeric_char8_t_get_10();
    test_numeric_char8_t_get_11();
    test_numeric_char8_t_get_12();
    test_numeric_char8_t_get_13();
    test_numeric_char8_t_get_14();
    test_numeric_char8_t_get_15();
    test_numeric_char8_t_get_16();
    test_numeric_char8_t_get_17();
    test_numeric_char8_t_get_18();
    test_numeric_char8_t_get_19();
    test_numeric_char8_t_get_20();
    test_numeric_char8_t_get_21();
}