# Generated by test/tools/derive_suites.py -- do not edit by hand.
#
# One entry per suite: the directory it is built from, and the functions its
# generated main() calls, in the order the aggregate main() it came from
# reached them.  Re-run the script after adding, removing or renaming a test
# function; `--check` verifies this file still matches the sources.

set(IOV2_TEST_SUITE_DIRS
    common
    concur
    cvt/code_cvt
    cvt/comp
    cvt/crypt
    cvt/cvt_io
    cvt/cvt_pipe_creator
    cvt/root_cvt
    cvt/runtime_cvt
    device/file_device
    device/mem_device
    device/std_device
    facet/collate
    facet/ctype
    facet/messages
    facet/monetary
    facet/numeric
    facet/timeio
    io/ctad
    io/io_base
    io/io_base/manipulators
    io/ios_state
    io/iostream/switch_to_get
    io/iostream/switch_to_put
    io/istream/attach
    io/istream/derive
    io/istream/extractors_arithmetic
    io/istream/extractors_character
    io/istream/extractors_time
    io/istream/get
    io/istream/getline
    io/istream/ignore
    io/istream/peek
    io/istream/putback
    io/istream/read
    io/istream/seek
    io/istream/tell
    io/istream/ws
    io/objects
    io/ostream/appmode
    io/ostream/callbacks
    io/ostream/cvt
    io/ostream/derive
    io/ostream/endl
    io/ostream/ends
    io/ostream/exceptions
    io/ostream/flush
    io/ostream/inserters_arithmetic
    io/ostream/inserters_character
    io/ostream/inserters_time
    io/ostream/seek
    io/ostream/tell
    io/ostream/tie
    io/stream_buf
    io/streambuf_iterator
    io/traits
    locale
)

# Suites whose sources are GoogleTest.  A directory appears here as soon as
# its first source is converted, not when the last one is: the generated
# main() can hold TEST()s and the remaining hand-written entry points at the
# same time, which is what lets a directory be converted one file at a time.
set(IOV2_TEST_GTEST_SUITE_DIRS
    common
    device/file_device
    device/mem_device
    device/std_device
)

# Sources nothing compiles: the aggregate main()s that test/Makefile
# built, and the dispatch-only files whose callers they were.  They remain in
# the tree because derive_suites.py reads them -- they are what fixes the
# entries below and their order.  See its module docstring.
set(IOV2_TEST_EXCLUDED_SOURCES
    concur/test_concur.cpp
    cvt/test_cvt.cpp
    facet/test_facet.cpp
    io/io_base/test_io_base.cpp
    io/iostream/test_iostream.cpp
    io/istream/test_istream.cpp
    io/ostream/test_ostream.cpp
    io/test_io.cpp
    locale/test_locale.cpp
)

set(IOV2_TEST_SOURCE_TOTAL_EXPECTED 187)

set(test_common_ENTRIES
    # none: every case registers itself
)

set(test_concur_ENTRIES
    test_concur_output_1
    test_concur_flush_1
    test_concur_sentryless_1
    test_concur_state_1
    test_concur_tie_1
    test_concur_tie_nonblocking_1
    test_concur_switch_1
    test_concur_endl_1
    test_concur_pword_1
    test_concur_assign_tie_target_1
    test_concur_copy_tie_source_1
    test_concur_copy_vs_state_1
    test_concur_move_assign_vs_state_1
    test_concur_attach_detach_1
    test_concur_iostream_crossed_1
    test_istream_sync_char_1
    test_istream_sync_wchar_t_1
    test_ostream_sync_char_1
    test_ostream_sync_wchar_t_1
)

set(test_cvt_code_cvt_ENTRIES
    test_code_cvt
)

set(test_cvt_comp_ENTRIES
    test_comp_cvt
)

set(test_cvt_crypt_ENTRIES
    test_crypt_cvt
)

set(test_cvt_cvt_io_ENTRIES
    test_cvt_io
)

set(test_cvt_cvt_pipe_creator_ENTRIES
    test_cvt_pipe_creator
)

set(test_cvt_root_cvt_ENTRIES
    test_root_cvt
)

set(test_cvt_runtime_cvt_ENTRIES
    test_runtime_cvt
)

set(test_device_file_device_ENTRIES
    # none: every case registers itself
)

set(test_device_mem_device_ENTRIES
    # none: every case registers itself
)

set(test_device_std_device_ENTRIES
    # none: every case registers itself
)

set(test_facet_collate_ENTRIES
    test_collate
)

set(test_facet_ctype_ENTRIES
    test_ctype
)

set(test_facet_messages_ENTRIES
    test_messages
)

set(test_facet_monetary_ENTRIES
    test_monetary
)

set(test_facet_numeric_ENTRIES
    test_numeric
)

set(test_facet_timeio_ENTRIES
    test_timeio
)

set(test_io_ctad_ENTRIES
    # none: this suite is compile-time only
)

set(test_io_io_base_ENTRIES
    test_io_base_char_fill_1
    test_io_base_char_fill_2
    test_io_base_char_fill_3
    test_io_base_wchar_t_fill_1
    test_io_base_wchar_t_fill_2
    test_io_base_width_1
    test_io_base_width_2
    test_io_base_width_3
    test_io_base_width_wchar_t_1
    test_io_base_boolalpha_1
    test_io_base_state_handle_exception_idempotent_1
    test_io_base_storage_1
    test_io_base_storage_2
    test_io_base_storage_3
    test_io_base_storage_4
)

set(test_io_io_base_manipulators_ENTRIES
    test_io_base_manipulators
)

set(test_io_ios_state_ENTRIES
    test_ios_state
)

set(test_io_iostream_switch_to_get_ENTRIES
    test_iostream_switch_to_get
)

set(test_io_iostream_switch_to_put_ENTRIES
    test_iostream_switch_to_put
)

set(test_io_istream_attach_ENTRIES
    test_istream_attach
)

set(test_io_istream_derive_ENTRIES
    test_istream_derive
)

set(test_io_istream_extractors_arithmetic_ENTRIES
    test_istream_extractors_arithmetic
)

set(test_io_istream_extractors_character_ENTRIES
    test_istream_extractors_character
)

set(test_io_istream_extractors_time_ENTRIES
    test_istream_extractors_time
)

set(test_io_istream_get_ENTRIES
    test_istream_get
)

set(test_io_istream_getline_ENTRIES
    test_istream_getline
)

set(test_io_istream_ignore_ENTRIES
    test_istream_ignore
)

set(test_io_istream_peek_ENTRIES
    test_istream_peek
)

set(test_io_istream_putback_ENTRIES
    test_istream_putback
)

set(test_io_istream_read_ENTRIES
    test_istream_read
)

set(test_io_istream_seek_ENTRIES
    test_istream_seek
)

set(test_io_istream_tell_ENTRIES
    test_istream_tell
)

set(test_io_istream_ws_ENTRIES
    test_istream_ws
)

set(test_io_objects_ENTRIES
    test_io_objects
)

set(test_io_ostream_appmode_ENTRIES
    test_ostream_appmode
)

set(test_io_ostream_callbacks_ENTRIES
    test_ostream_callbacks
)

set(test_io_ostream_cvt_ENTRIES
    test_ostream_cvt
)

set(test_io_ostream_derive_ENTRIES
    test_ostream_derive
)

set(test_io_ostream_endl_ENTRIES
    test_ostream_endl
)

set(test_io_ostream_ends_ENTRIES
    test_ostream_ends
)

set(test_io_ostream_exceptions_ENTRIES
    test_ostream_exceptions
)

set(test_io_ostream_flush_ENTRIES
    test_ostream_flush
)

set(test_io_ostream_inserters_arithmetic_ENTRIES
    test_ostream_inserters_arithmetic
)

set(test_io_ostream_inserters_character_ENTRIES
    test_ostream_inserters_character
)

set(test_io_ostream_inserters_time_ENTRIES
    test_ostream_inserters_time
)

set(test_io_ostream_seek_ENTRIES
    test_ostream_seek
)

set(test_io_ostream_tell_ENTRIES
    test_ostream_tell
)

set(test_io_ostream_tie_ENTRIES
    test_ostream_tie
)

set(test_io_stream_buf_ENTRIES
    test_streambuf
)

set(test_io_streambuf_iterator_ENTRIES
    test_streambuf_iterator
)

set(test_io_traits_ENTRIES
    test_io_traits
)

set(test_locale_ENTRIES
    test_locale_char_traits
    test_locale_char_1
    test_locale_char_2
    test_locale_char_3
    test_locale_char_4
    test_locale_char_5
    test_locale_char_6
    test_locale_char_7
    test_locale_char_8
    test_locale_char_9
    test_locale_char_10
    test_locale_char_11
    test_locale_wchar_t_traits
    test_locale_wchar_t_1
    test_locale_wchar_t_2
    test_locale_wchar_t_3
    test_locale_wchar_t_4
    test_locale_wchar_t_5
    test_locale_wchar_t_6
    test_locale_wchar_t_7
    test_locale_wchar_t_8
    test_locale_wchar_t_9
    test_locale_wchar_t_10
    test_locale_char32_t_traits
    test_locale_char32_t_1
    test_locale_char32_t_2
    test_locale_char32_t_3
    test_locale_char32_t_4
    test_locale_char32_t_5
    test_locale_char32_t_6
    test_locale_char32_t_7
    test_locale_char32_t_8
    test_locale_char32_t_9
    test_locale_char32_t_10
    test_locale_char8_t_traits
    test_locale_char8_t_1
    test_locale_char8_t_2
    test_locale_char8_t_3
    test_locale_char8_t_4
    test_locale_char8_t_5
    test_locale_char8_t_6
    test_locale_char8_t_7
    test_locale_char8_t_8
    test_locale_char8_t_9
    test_locale_char8_t_10
)
