void test_timeio_char_put_1();
void test_timeio_char_put_2();
void test_timeio_char_put_3();
void test_timeio_char_put_4();
void test_timeio_char_put_5();
void test_timeio_char_put_6();
void test_timeio_char_put_7();
void test_timeio_char_put_8();
void test_timeio_char_put_9();
void test_timeio_char_put_10();
void test_timeio_char_put_11();
void test_timeio_char_put_12();
void test_timeio_char_put_13();
void test_timeio_char_put_14();
void test_timeio_char_put_15();
void test_timeio_char_put_16();
void test_timeio_char_put_17();
void test_timeio_char_get_1();
void test_timeio_char_get_2();
void test_timeio_char_get_3();
void test_timeio_char_get_4();
void test_timeio_char_get_5();
void test_timeio_char_get_6();
void test_timeio_char_get_7();
void test_timeio_char_get_8();
void test_timeio_char_get_9();
void test_timeio_char_get_10();
void test_timeio_char_get_11();
void test_timeio_char_get_12();
void test_timeio_char_get_13();
void test_timeio_char_get_14();
void test_timeio_char_get_15();
void test_timeio_char_get_16();
void test_timeio_char_get_17();

void test_timeio_wchar_t_put_1();
void test_timeio_wchar_t_put_2();
void test_timeio_wchar_t_put_3();
void test_timeio_wchar_t_put_4();
void test_timeio_wchar_t_put_5();
void test_timeio_wchar_t_put_6();
void test_timeio_wchar_t_put_7();
void test_timeio_wchar_t_put_8();
void test_timeio_wchar_t_put_9();
void test_timeio_wchar_t_put_10();
void test_timeio_wchar_t_put_11();
void test_timeio_wchar_t_put_12();
void test_timeio_wchar_t_put_13();
void test_timeio_wchar_t_put_14();
void test_timeio_wchar_t_put_15();
void test_timeio_wchar_t_put_16();
void test_timeio_wchar_t_put_17();
void test_timeio_wchar_t_get_1();
void test_timeio_wchar_t_get_2();
void test_timeio_wchar_t_get_3();
void test_timeio_wchar_t_get_4();
void test_timeio_wchar_t_get_5();
void test_timeio_wchar_t_get_6();
void test_timeio_wchar_t_get_7();
void test_timeio_wchar_t_get_8();
void test_timeio_wchar_t_get_9();
void test_timeio_wchar_t_get_10();
void test_timeio_wchar_t_get_11();
void test_timeio_wchar_t_get_12();

void test_timeio_char32_t_put_1();
void test_timeio_char32_t_put_2();
void test_timeio_char32_t_put_3();
void test_timeio_char32_t_put_4();
void test_timeio_char32_t_put_5();
void test_timeio_char32_t_put_6();
void test_timeio_char32_t_put_7();
void test_timeio_char32_t_put_8();
void test_timeio_char32_t_put_9();
void test_timeio_char32_t_put_10();
void test_timeio_char32_t_put_11();
void test_timeio_char32_t_put_12();
void test_timeio_char32_t_put_13();
void test_timeio_char32_t_put_14();
void test_timeio_char32_t_put_15();
void test_timeio_char32_t_put_16();
void test_timeio_char32_t_put_17();
void test_timeio_char32_t_get_1();
void test_timeio_char32_t_get_2();
void test_timeio_char32_t_get_3();
void test_timeio_char32_t_get_4();
void test_timeio_char32_t_get_5();
void test_timeio_char32_t_get_6();
void test_timeio_char32_t_get_7();
void test_timeio_char32_t_get_8();
void test_timeio_char32_t_get_9();
void test_timeio_char32_t_get_10();
void test_timeio_char32_t_get_11();
void test_timeio_char32_t_get_12();

void test_timeio_char8_t_put_1();
void test_timeio_char8_t_put_2();
void test_timeio_char8_t_put_3();
void test_timeio_char8_t_put_4();
void test_timeio_char8_t_put_5();
void test_timeio_char8_t_put_6();
void test_timeio_char8_t_put_7();
void test_timeio_char8_t_put_8();
void test_timeio_char8_t_put_9();
void test_timeio_char8_t_put_10();
void test_timeio_char8_t_put_11();
void test_timeio_char8_t_put_12();
void test_timeio_char8_t_put_13();
void test_timeio_char8_t_put_14();
void test_timeio_char8_t_put_15();
void test_timeio_char8_t_put_16();
void test_timeio_char8_t_put_17();
void test_timeio_char8_t_get_1();
void test_timeio_char8_t_get_2();
void test_timeio_char8_t_get_3();
void test_timeio_char8_t_get_4();
void test_timeio_char8_t_get_5();
void test_timeio_char8_t_get_6();
void test_timeio_char8_t_get_7();
void test_timeio_char8_t_get_8();
void test_timeio_char8_t_get_9();
void test_timeio_char8_t_get_10();
void test_timeio_char8_t_get_11();
void test_timeio_char8_t_get_12();

void test_timeio()
{
    test_timeio_char_put_1();
    test_timeio_char_put_2();
    test_timeio_char_put_3();
    test_timeio_char_put_4();
    test_timeio_char_put_5();
    test_timeio_char_put_6();
    test_timeio_char_put_7();
    test_timeio_char_put_8();
    test_timeio_char_put_9();
    test_timeio_char_put_10();
    test_timeio_char_put_11();
    test_timeio_char_put_12();
    test_timeio_char_put_13();
    test_timeio_char_put_14();
    test_timeio_char_put_15();
    test_timeio_char_put_16();
    test_timeio_char_put_17();
    test_timeio_char_get_1();
    test_timeio_char_get_2();
    test_timeio_char_get_3();
    test_timeio_char_get_4();
    test_timeio_char_get_5();
    test_timeio_char_get_6();
    test_timeio_char_get_7();
    test_timeio_char_get_8();
    test_timeio_char_get_9();
    test_timeio_char_get_10();
    test_timeio_char_get_11();
    test_timeio_char_get_12();
    test_timeio_char_get_13();
    test_timeio_char_get_14();
    test_timeio_char_get_15();
    test_timeio_char_get_16();
    test_timeio_char_get_17();
    
    test_timeio_wchar_t_put_1();
    test_timeio_wchar_t_put_2();
    test_timeio_wchar_t_put_3();
    test_timeio_wchar_t_put_4();
    test_timeio_wchar_t_put_5();
    test_timeio_wchar_t_put_6();
    test_timeio_wchar_t_put_7();
    test_timeio_wchar_t_put_8();
    test_timeio_wchar_t_put_9();
    test_timeio_wchar_t_put_10();
    test_timeio_wchar_t_put_11();
    test_timeio_wchar_t_put_12();
    test_timeio_wchar_t_put_13();
    test_timeio_wchar_t_put_14();
    test_timeio_wchar_t_put_15();
    test_timeio_wchar_t_put_16();
    test_timeio_wchar_t_put_17();
    test_timeio_wchar_t_get_1();
    test_timeio_wchar_t_get_2();
    test_timeio_wchar_t_get_3();
    test_timeio_wchar_t_get_4();
    test_timeio_wchar_t_get_5();
    test_timeio_wchar_t_get_6();
    test_timeio_wchar_t_get_7();
    test_timeio_wchar_t_get_8();
    test_timeio_wchar_t_get_9();
    test_timeio_wchar_t_get_10();
    test_timeio_wchar_t_get_11();
    test_timeio_wchar_t_get_12();

    test_timeio_char32_t_put_1();
    test_timeio_char32_t_put_2();
    test_timeio_char32_t_put_3();
    test_timeio_char32_t_put_4();
    test_timeio_char32_t_put_5();
    test_timeio_char32_t_put_6();
    test_timeio_char32_t_put_7();
    test_timeio_char32_t_put_8();
    test_timeio_char32_t_put_9();
    test_timeio_char32_t_put_10();
    test_timeio_char32_t_put_11();
    test_timeio_char32_t_put_12();
    test_timeio_char32_t_put_13();
    test_timeio_char32_t_put_14();
    test_timeio_char32_t_put_15();
    test_timeio_char32_t_put_16();
    test_timeio_char32_t_put_17();
    test_timeio_char32_t_get_1();
    test_timeio_char32_t_get_2();
    test_timeio_char32_t_get_3();
    test_timeio_char32_t_get_4();
    test_timeio_char32_t_get_5();
    test_timeio_char32_t_get_6();
    test_timeio_char32_t_get_7();
    test_timeio_char32_t_get_8();
    test_timeio_char32_t_get_9();
    test_timeio_char32_t_get_10();
    test_timeio_char32_t_get_11();
    test_timeio_char32_t_get_12();

    test_timeio_char8_t_put_1();
    test_timeio_char8_t_put_2();
    test_timeio_char8_t_put_3();
    test_timeio_char8_t_put_4();
    test_timeio_char8_t_put_5();
    test_timeio_char8_t_put_6();
    test_timeio_char8_t_put_7();
    test_timeio_char8_t_put_8();
    test_timeio_char8_t_put_9();
    test_timeio_char8_t_put_10();
    test_timeio_char8_t_put_11();
    test_timeio_char8_t_put_12();
    test_timeio_char8_t_put_13();
    test_timeio_char8_t_put_14();
    test_timeio_char8_t_put_15();
    test_timeio_char8_t_put_16();
    test_timeio_char8_t_put_17();
    test_timeio_char8_t_get_1();
    test_timeio_char8_t_get_2();
    test_timeio_char8_t_get_3();
    test_timeio_char8_t_get_4();
    test_timeio_char8_t_get_5();
    test_timeio_char8_t_get_6();
    test_timeio_char8_t_get_7();
    test_timeio_char8_t_get_8();
    test_timeio_char8_t_get_9();
    test_timeio_char8_t_get_10();
    test_timeio_char8_t_get_11();
    test_timeio_char8_t_get_12();
}