void test_monetary_char_common_1();
void test_monetary_char_common_2();
void test_monetary_char_put_1();
void test_monetary_char_put_2();
void test_monetary_char_put_3();
void test_monetary_char_put_4();
void test_monetary_char_put_5();
void test_monetary_char_put_6();
void test_monetary_char_put_7();
void test_monetary_char_get_1();
void test_monetary_char_get_2();
void test_monetary_char_get_3();
void test_monetary_char_get_4();
void test_monetary_char_get_5();
void test_monetary_char_get_6();
void test_monetary_char_get_7();
void test_monetary_char_get_8();
void test_monetary_char_get_9();
void test_monetary_char_get_10();
void test_monetary_char_get_11();
void test_monetary_char_get_12();
void test_monetary_char_get_13();
void test_monetary_char_get_14();
void test_monetary_char_get_15();
void test_monetary_char_get_16();
void test_monetary_char_get_17();
void test_monetary_char_get_18();
void test_monetary_char_get_19();
void test_monetary_char_get_20();
void test_monetary_char_get_21();
void test_monetary_char_get_22();
void test_monetary_char_get_23();
void test_monetary_char_get_24();
void test_monetary_char_get_25();
void test_monetary_char_get_26();
void test_monetary_char_get_27();
void test_monetary_char_get_28();
void test_monetary_char_get_29();
void test_monetary_char_get_30();
void test_monetary_char_get_31();
void test_monetary_char_get_32();
void test_monetary_char_get_33();
void test_monetary_char_get_34();
void test_monetary_char_get_35();
void test_monetary_char_get_36();
void test_monetary_char_get_37();
void test_monetary_char_get_38();
void test_monetary_char_get_39();
void test_monetary_char_get_40();
void test_monetary_char_get_41();
void test_monetary_char_get_42();
void test_monetary_char_get_43();
void test_monetary_char_get_44();
void test_monetary_char_get_45();
void test_monetary_char_get_46();

void test_monetary_wchar_t_common_1();
void test_monetary_wchar_t_common_2();
void test_monetary_wchar_t_put_1();
void test_monetary_wchar_t_put_2();
void test_monetary_wchar_t_put_3();
void test_monetary_wchar_t_put_4();
void test_monetary_wchar_t_put_5();
void test_monetary_wchar_t_put_6();
void test_monetary_wchar_t_put_7();
void test_monetary_wchar_t_get_1();
void test_monetary_wchar_t_get_2();
void test_monetary_wchar_t_get_3();
void test_monetary_wchar_t_get_4();
void test_monetary_wchar_t_get_5();
void test_monetary_wchar_t_get_6();
void test_monetary_wchar_t_get_7();
void test_monetary_wchar_t_get_8();
void test_monetary_wchar_t_get_9();
void test_monetary_wchar_t_get_10();
void test_monetary_wchar_t_get_11();
void test_monetary_wchar_t_get_12();
void test_monetary_wchar_t_get_13();
void test_monetary_wchar_t_get_14();
void test_monetary_wchar_t_get_15();
void test_monetary_wchar_t_get_16();
void test_monetary_wchar_t_get_17();
void test_monetary_wchar_t_get_18();
void test_monetary_wchar_t_get_19();
void test_monetary_wchar_t_get_20();
void test_monetary_wchar_t_get_21();
void test_monetary_wchar_t_get_22();
void test_monetary_wchar_t_get_23();

void test_monetary_char32_t_common_1();
void test_monetary_char32_t_common_2();
void test_monetary_char32_t_put_1();
void test_monetary_char32_t_put_2();
void test_monetary_char32_t_put_3();
void test_monetary_char32_t_put_4();
void test_monetary_char32_t_put_5();
void test_monetary_char32_t_put_6();
void test_monetary_char32_t_put_7();
void test_monetary_char32_t_get_1();
void test_monetary_char32_t_get_2();
void test_monetary_char32_t_get_3();
void test_monetary_char32_t_get_4();
void test_monetary_char32_t_get_5();
void test_monetary_char32_t_get_6();
void test_monetary_char32_t_get_7();
void test_monetary_char32_t_get_8();
void test_monetary_char32_t_get_9();
void test_monetary_char32_t_get_10();
void test_monetary_char32_t_get_11();
void test_monetary_char32_t_get_12();
void test_monetary_char32_t_get_13();
void test_monetary_char32_t_get_14();
void test_monetary_char32_t_get_15();
void test_monetary_char32_t_get_16();
void test_monetary_char32_t_get_17();
void test_monetary_char32_t_get_18();
void test_monetary_char32_t_get_19();
void test_monetary_char32_t_get_20();
void test_monetary_char32_t_get_21();
void test_monetary_char32_t_get_22();
void test_monetary_char32_t_get_23();

void test_monetary_char8_t_common_1();
void test_monetary_char8_t_common_2();
void test_monetary_char8_t_put_1();
void test_monetary_char8_t_put_2();
void test_monetary_char8_t_put_3();
void test_monetary_char8_t_put_4();
void test_monetary_char8_t_put_5();
void test_monetary_char8_t_put_6();
void test_monetary_char8_t_put_7();
void test_monetary_char8_t_get_1();
void test_monetary_char8_t_get_2();
void test_monetary_char8_t_get_3();
void test_monetary_char8_t_get_4();
void test_monetary_char8_t_get_5();
void test_monetary_char8_t_get_6();
void test_monetary_char8_t_get_7();
void test_monetary_char8_t_get_8();
void test_monetary_char8_t_get_9();
void test_monetary_char8_t_get_10();
void test_monetary_char8_t_get_11();
void test_monetary_char8_t_get_12();
void test_monetary_char8_t_get_13();
void test_monetary_char8_t_get_14();
void test_monetary_char8_t_get_15();
void test_monetary_char8_t_get_16();
void test_monetary_char8_t_get_17();
void test_monetary_char8_t_get_18();
void test_monetary_char8_t_get_19();
void test_monetary_char8_t_get_20();
void test_monetary_char8_t_get_21();
void test_monetary_char8_t_get_22();
void test_monetary_char8_t_get_23();

void test_monetary()
{
    test_monetary_char_common_1();
    test_monetary_char_common_2();
    test_monetary_char_put_1();
    test_monetary_char_put_2();
    test_monetary_char_put_3();
    test_monetary_char_put_4();
    test_monetary_char_put_5();
    test_monetary_char_put_6();
    test_monetary_char_put_7();
    test_monetary_char_get_1();
    test_monetary_char_get_2();
    test_monetary_char_get_3();
    test_monetary_char_get_4();
    test_monetary_char_get_5();
    test_monetary_char_get_6();
    test_monetary_char_get_7();
    test_monetary_char_get_8();
    test_monetary_char_get_9();
    test_monetary_char_get_10();
    test_monetary_char_get_11();
    test_monetary_char_get_12();
    test_monetary_char_get_13();
    test_monetary_char_get_14();
    test_monetary_char_get_15();
    test_monetary_char_get_16();
    test_monetary_char_get_17();
    test_monetary_char_get_18();
    test_monetary_char_get_19();
    test_monetary_char_get_20();
    test_monetary_char_get_21();
    test_monetary_char_get_22();
    test_monetary_char_get_23();
    test_monetary_char_get_24();
    test_monetary_char_get_25();
    test_monetary_char_get_26();
    test_monetary_char_get_27();
    test_monetary_char_get_28();
    test_monetary_char_get_29();
    test_monetary_char_get_30();
    test_monetary_char_get_31();
    test_monetary_char_get_32();
    test_monetary_char_get_33();
    test_monetary_char_get_34();
    test_monetary_char_get_35();
    test_monetary_char_get_36();
    test_monetary_char_get_37();
    test_monetary_char_get_38();
    test_monetary_char_get_39();
    test_monetary_char_get_40();
    test_monetary_char_get_41();
    test_monetary_char_get_42();
    test_monetary_char_get_43();
    test_monetary_char_get_44();
    test_monetary_char_get_45();
    test_monetary_char_get_46();
    
    test_monetary_wchar_t_common_1();
    test_monetary_wchar_t_common_2();
    test_monetary_wchar_t_put_1();
    test_monetary_wchar_t_put_2();
    test_monetary_wchar_t_put_3();
    test_monetary_wchar_t_put_4();
    test_monetary_wchar_t_put_5();
    test_monetary_wchar_t_put_6();
    test_monetary_wchar_t_put_7();
    test_monetary_wchar_t_get_1();
    test_monetary_wchar_t_get_2();
    test_monetary_wchar_t_get_3();
    test_monetary_wchar_t_get_4();
    test_monetary_wchar_t_get_5();
    test_monetary_wchar_t_get_6();
    test_monetary_wchar_t_get_7();
    test_monetary_wchar_t_get_8();
    test_monetary_wchar_t_get_9();
    test_monetary_wchar_t_get_10();
    test_monetary_wchar_t_get_11();
    test_monetary_wchar_t_get_12();
    test_monetary_wchar_t_get_13();
    test_monetary_wchar_t_get_15();
    test_monetary_wchar_t_get_16();
    test_monetary_wchar_t_get_17();
    test_monetary_wchar_t_get_18();
    test_monetary_wchar_t_get_19();
    test_monetary_wchar_t_get_20();
    test_monetary_wchar_t_get_21();
    test_monetary_wchar_t_get_22();
    test_monetary_wchar_t_get_23();

    test_monetary_char32_t_common_1();
    test_monetary_char32_t_common_2();
    test_monetary_char32_t_put_1();
    test_monetary_char32_t_put_2();
    test_monetary_char32_t_put_3();
    test_monetary_char32_t_put_4();
    test_monetary_char32_t_put_5();
    test_monetary_char32_t_put_6();
    test_monetary_char32_t_put_7();
    test_monetary_char32_t_get_1();
    test_monetary_char32_t_get_2();
    test_monetary_char32_t_get_3();
    test_monetary_char32_t_get_4();
    test_monetary_char32_t_get_5();
    test_monetary_char32_t_get_6();
    test_monetary_char32_t_get_7();
    test_monetary_char32_t_get_8();
    test_monetary_char32_t_get_9();
    test_monetary_char32_t_get_10();
    test_monetary_char32_t_get_11();
    test_monetary_char32_t_get_12();
    test_monetary_char32_t_get_13();
    test_monetary_char32_t_get_14();
    test_monetary_char32_t_get_15();
    test_monetary_char32_t_get_16();
    test_monetary_char32_t_get_17();
    test_monetary_char32_t_get_18();
    test_monetary_char32_t_get_19();
    test_monetary_char32_t_get_20();
    test_monetary_char32_t_get_21();
    test_monetary_char32_t_get_22();
    test_monetary_char32_t_get_23();

    test_monetary_char8_t_common_1();
    test_monetary_char8_t_common_2();
    test_monetary_char8_t_put_1();
    test_monetary_char8_t_put_2();
    test_monetary_char8_t_put_3();
    test_monetary_char8_t_put_4();
    test_monetary_char8_t_put_5();
    test_monetary_char8_t_put_6();
    test_monetary_char8_t_put_7();
    test_monetary_char8_t_get_1();
    test_monetary_char8_t_get_2();
    test_monetary_char8_t_get_3();
    test_monetary_char8_t_get_4();
    test_monetary_char8_t_get_5();
    test_monetary_char8_t_get_6();
    test_monetary_char8_t_get_7();
    test_monetary_char8_t_get_8();
    test_monetary_char8_t_get_9();
    test_monetary_char8_t_get_10();
    test_monetary_char8_t_get_11();
    test_monetary_char8_t_get_12();
    test_monetary_char8_t_get_13();
    test_monetary_char8_t_get_14();
    test_monetary_char8_t_get_15();
    test_monetary_char8_t_get_16();
    test_monetary_char8_t_get_17();
    test_monetary_char8_t_get_18();
    test_monetary_char8_t_get_19();
    test_monetary_char8_t_get_20();
    test_monetary_char8_t_get_21();
    test_monetary_char8_t_get_22();
    test_monetary_char8_t_get_23();
}