void test_code_cvt_mem_char_gen_1();
void test_code_cvt_mem_char_gen_2();
void test_code_cvt_mem_char_gen_3();
void test_code_cvt_mem_char_gen_4();
void test_code_cvt_mem_char_gen_5();
void test_code_cvt_mem_char_bos_1();
void test_code_cvt_mem_char_bos_2();
void test_code_cvt_mem_char_bos_3();
void test_code_cvt_mem_char_bos_4();
void test_code_cvt_mem_char_bos_5();
void test_code_cvt_mem_char_get_1();
void test_code_cvt_mem_char_get_nra_1();
void test_code_cvt_mem_char_put_1();
void test_code_cvt_mem_char_put_2();
void test_code_cvt_mem_char_put_3();
void test_code_cvt_mem_char_put_4();
void test_code_cvt_mem_char_flush_1();
void test_code_cvt_mem_char_flush_2();
void test_code_cvt_mem_char_flush_3();
void test_code_cvt_mem_char_seek_1();
void test_code_cvt_mem_char_seek_2();
void test_code_cvt_mem_char_seek_3();
void test_code_cvt_mem_char_seek_4();
void test_code_cvt_mem_char_rseek_1();
void test_code_cvt_mem_char_rseek_2();
void test_code_cvt_mem_char_rseek_3();
void test_code_cvt_mem_char_rseek_4();
void test_code_cvt_mem_char_io_1();
void test_code_cvt_mem_char_io_2();
void test_code_cvt_mem_char_io_3();
void test_code_cvt_mem_char_io_4();

void test_code_cvt_mem_char8_t_gen_1();
void test_code_cvt_mem_char8_t_gen_2();
void test_code_cvt_mem_char8_t_gen_3();
void test_code_cvt_mem_char8_t_gen_4();
void test_code_cvt_mem_char8_t_gen_5();
void test_code_cvt_mem_char8_t_bos_1();
void test_code_cvt_mem_char8_t_bos_2();
void test_code_cvt_mem_char8_t_bos_3();
void test_code_cvt_mem_char8_t_bos_4();
void test_code_cvt_mem_char8_t_bos_5();
void test_code_cvt_mem_char8_t_get_1();
void test_code_cvt_mem_char8_t_get_nra_1();
void test_code_cvt_mem_char8_t_put_1();
void test_code_cvt_mem_char8_t_put_2();
void test_code_cvt_mem_char8_t_flush_1();
void test_code_cvt_mem_char8_t_flush_2();
void test_code_cvt_mem_char8_t_seek_1();
void test_code_cvt_mem_char8_t_seek_2();
void test_code_cvt_mem_char8_t_rseek_1();
void test_code_cvt_mem_char8_t_rseek_2();
void test_code_cvt_mem_char8_t_io_1();
void test_code_cvt_mem_char8_t_io_2();

void test_code_cvt_mem_char8_t_wchar_t_gen_1();
void test_code_cvt_mem_char8_t_wchar_t_gen_2();
void test_code_cvt_mem_char8_t_wchar_t_gen_3();
void test_code_cvt_mem_char8_t_wchar_t_gen_4();
void test_code_cvt_mem_char8_t_wchar_t_gen_5();
void test_code_cvt_mem_char8_t_wchar_t_bos_1();
void test_code_cvt_mem_char8_t_wchar_t_bos_2();
void test_code_cvt_mem_char8_t_wchar_t_bos_3();
void test_code_cvt_mem_char8_t_wchar_t_bos_4();
void test_code_cvt_mem_char8_t_wchar_t_bos_5();
void test_code_cvt_mem_char8_t_wchar_t_get_1();
void test_code_cvt_mem_char8_t_wchar_t_get_nra_1();
void test_code_cvt_mem_char8_t_wchar_t_put_1();
void test_code_cvt_mem_char8_t_wchar_t_put_2();
void test_code_cvt_mem_char8_t_wchar_t_flush_1();
void test_code_cvt_mem_char8_t_wchar_t_flush_2();
void test_code_cvt_mem_char8_t_wchar_t_seek_1();
void test_code_cvt_mem_char8_t_wchar_t_seek_2();
void test_code_cvt_mem_char8_t_wchar_t_rseek_1();
void test_code_cvt_mem_char8_t_wchar_t_rseek_2();
void test_code_cvt_mem_char8_t_wchar_t_io_1();
void test_code_cvt_mem_char8_t_wchar_t_io_2();

void test_code_cvt_stdio_char_gen_1();
void test_code_cvt_stdio_char_gen_2();
void test_code_cvt_stdio_char_gen_3();
void test_code_cvt_stdio_char_bos_1();
void test_code_cvt_stdio_char_bos_2();
void test_code_cvt_stdio_char_bos_3();
void test_code_cvt_stdio_char_bos_4();
void test_code_cvt_stdio_char_bos_5();
void test_code_cvt_stdio_char_bos_6();
void test_code_cvt_stdio_char_get_1();
void test_code_cvt_stdio_char_get_nra_1();
void test_code_cvt_stdio_char_put_1();
void test_code_cvt_stdio_char_put_2();

void test_code_cvt()
{
    test_code_cvt_mem_char_gen_1();
    test_code_cvt_mem_char_gen_2();
    test_code_cvt_mem_char_gen_3();
    test_code_cvt_mem_char_gen_4();
    test_code_cvt_mem_char_gen_5();
    test_code_cvt_mem_char_bos_1();
    test_code_cvt_mem_char_bos_2();
    test_code_cvt_mem_char_bos_3();
    test_code_cvt_mem_char_bos_4();
    test_code_cvt_mem_char_bos_5();
    test_code_cvt_mem_char_get_1();
    test_code_cvt_mem_char_get_nra_1();
    test_code_cvt_mem_char_put_1();
    test_code_cvt_mem_char_put_2();
    test_code_cvt_mem_char_put_3();
    test_code_cvt_mem_char_put_4();
    test_code_cvt_mem_char_flush_1();
    test_code_cvt_mem_char_flush_2();
    test_code_cvt_mem_char_flush_3();
    test_code_cvt_mem_char_seek_1();
    test_code_cvt_mem_char_seek_2();
    test_code_cvt_mem_char_seek_3();
    test_code_cvt_mem_char_seek_4();
    test_code_cvt_mem_char_rseek_1();
    test_code_cvt_mem_char_rseek_2();
    test_code_cvt_mem_char_rseek_3();
    test_code_cvt_mem_char_rseek_4();
    test_code_cvt_mem_char_io_1();
    test_code_cvt_mem_char_io_2();
    test_code_cvt_mem_char_io_3();
    test_code_cvt_mem_char_io_4();
    
    test_code_cvt_mem_char8_t_gen_1();
    test_code_cvt_mem_char8_t_gen_2();
    test_code_cvt_mem_char8_t_gen_3();
    test_code_cvt_mem_char8_t_gen_4();
    test_code_cvt_mem_char8_t_gen_5();
    test_code_cvt_mem_char8_t_bos_1();
    test_code_cvt_mem_char8_t_bos_2();
    test_code_cvt_mem_char8_t_bos_3();
    test_code_cvt_mem_char8_t_bos_4();
    test_code_cvt_mem_char8_t_bos_5();
    test_code_cvt_mem_char8_t_get_1();
    test_code_cvt_mem_char8_t_get_nra_1();
    test_code_cvt_mem_char8_t_put_1();
    test_code_cvt_mem_char8_t_put_2();
    test_code_cvt_mem_char8_t_flush_1();
    test_code_cvt_mem_char8_t_flush_2();
    test_code_cvt_mem_char8_t_seek_1();
    test_code_cvt_mem_char8_t_seek_2();
    test_code_cvt_mem_char8_t_rseek_1();
    test_code_cvt_mem_char8_t_rseek_2();
    test_code_cvt_mem_char8_t_io_1();
    test_code_cvt_mem_char8_t_io_2();

    test_code_cvt_mem_char8_t_wchar_t_gen_1();
    test_code_cvt_mem_char8_t_wchar_t_gen_2();
    test_code_cvt_mem_char8_t_wchar_t_gen_3();
    test_code_cvt_mem_char8_t_wchar_t_gen_4();
    test_code_cvt_mem_char8_t_wchar_t_gen_5();
    test_code_cvt_mem_char8_t_wchar_t_bos_1();
    test_code_cvt_mem_char8_t_wchar_t_bos_2();
    test_code_cvt_mem_char8_t_wchar_t_bos_3();
    test_code_cvt_mem_char8_t_wchar_t_bos_4();
    test_code_cvt_mem_char8_t_wchar_t_bos_5();
    test_code_cvt_mem_char8_t_wchar_t_get_1();
    test_code_cvt_mem_char8_t_wchar_t_get_nra_1();
    test_code_cvt_mem_char8_t_wchar_t_put_1();
    test_code_cvt_mem_char8_t_wchar_t_put_2();
    test_code_cvt_mem_char8_t_wchar_t_flush_1();
    test_code_cvt_mem_char8_t_wchar_t_flush_2();
    test_code_cvt_mem_char8_t_wchar_t_seek_1();
    test_code_cvt_mem_char8_t_wchar_t_seek_2();
    test_code_cvt_mem_char8_t_wchar_t_rseek_1();
    test_code_cvt_mem_char8_t_wchar_t_rseek_2();
    test_code_cvt_mem_char8_t_wchar_t_io_1();
    test_code_cvt_mem_char8_t_wchar_t_io_2();
    
    test_code_cvt_stdio_char_gen_1();
    test_code_cvt_stdio_char_gen_2();
    test_code_cvt_stdio_char_gen_3();
    test_code_cvt_stdio_char_bos_1();
    test_code_cvt_stdio_char_bos_2();
    test_code_cvt_stdio_char_bos_3();
    test_code_cvt_stdio_char_bos_4();
    test_code_cvt_stdio_char_bos_5();
    test_code_cvt_stdio_char_bos_6();
    test_code_cvt_stdio_char_get_1();
    test_code_cvt_stdio_char_put_1();
    test_code_cvt_stdio_char_put_2();
}