void test_mem_device_char_gen_1();
void test_mem_device_char_gen_2();
void test_mem_device_char_gen_3();
void test_mem_device_char_in_1();
void test_mem_device_char_in_2();
void test_mem_device_char_in_3();
void test_mem_device_char_out_1();
void test_mem_device_char_out_2();
void test_mem_device_char_out_3();
void test_mem_device_char_io_1();
void test_mem_device_char_io_2();

void test_mem_device_wchar_t_gen_1();
void test_mem_device_wchar_t_gen_2();
void test_mem_device_wchar_t_gen_3();
void test_mem_device_wchar_t_in_1();
void test_mem_device_wchar_t_in_2();
void test_mem_device_wchar_t_in_3();
void test_mem_device_wchar_t_out_1();
void test_mem_device_wchar_t_out_2();
void test_mem_device_wchar_t_out_3();
void test_mem_device_wchar_t_io_1();
void test_mem_device_wchar_t_io_2();

void test_mem_device_char32_t_gen_1();
void test_mem_device_char32_t_gen_2();
void test_mem_device_char32_t_gen_3();
void test_mem_device_char32_t_in_1();
void test_mem_device_char32_t_in_2();
void test_mem_device_char32_t_in_3();
void test_mem_device_char32_t_out_1();
void test_mem_device_char32_t_out_2();
void test_mem_device_char32_t_out_3();
void test_mem_device_char32_t_io_1();
void test_mem_device_char32_t_io_2();

void test_mem_device_char8_t_gen_1();
void test_mem_device_char8_t_gen_2();
void test_mem_device_char8_t_gen_3();
void test_mem_device_char8_t_in_1();
void test_mem_device_char8_t_in_2();
void test_mem_device_char8_t_in_3();
void test_mem_device_char8_t_out_1();
void test_mem_device_char8_t_out_2();
void test_mem_device_char8_t_out_3();
void test_mem_device_char8_t_io_1();
void test_mem_device_char8_t_io_2();

void test_std_device_gen_1();
void test_std_device_input_1();
void test_std_device_output_1();
void test_std_device_output_2();

void test_file_device_char_gen_1();
void test_file_device_char_close_1();
void test_file_device_char_close_2();
void test_file_device_char_is_open_1();
void test_file_device_char_is_open_2();
void test_file_device_char_get_1();
void test_file_device_char_get_2();
void test_file_device_char_get_3();
void test_file_device_char_seek_1();
void test_file_device_char_seek_2();
void test_file_device_char_seek_3();
void test_file_device_char_seek_4();
void test_file_device_char_seek_5();
void test_file_device_char_seek_6();
void test_file_device_char_seek_7();
void test_file_device_char_seek_8();

void test_file_device_char8_t_gen_1();
void test_file_device_char8_t_close_1();
void test_file_device_char8_t_close_2();
void test_file_device_char8_t_is_open_1();
void test_file_device_char8_t_is_open_2();
void test_file_device_char8_t_get_1();
void test_file_device_char8_t_get_2();
void test_file_device_char8_t_get_3();
void test_file_device_char8_t_seek_1();
void test_file_device_char8_t_seek_2();
void test_file_device_char8_t_seek_3();
void test_file_device_char8_t_seek_4();
void test_file_device_char8_t_seek_5();
void test_file_device_char8_t_seek_6();
void test_file_device_char8_t_seek_7();
void test_file_device_char8_t_seek_8();

void test_device()
{
    test_mem_device_char_gen_1();
    test_mem_device_char_gen_2();
    test_mem_device_char_gen_3();
    test_mem_device_char_in_1();
    test_mem_device_char_in_2();
    test_mem_device_char_in_3();
    test_mem_device_char_out_1();
    test_mem_device_char_out_2();
    test_mem_device_char_out_3();
    test_mem_device_char_io_1();
    test_mem_device_char_io_2();

    test_mem_device_wchar_t_gen_1();
    test_mem_device_wchar_t_gen_2();
    test_mem_device_wchar_t_gen_3();
    test_mem_device_wchar_t_in_1();
    test_mem_device_wchar_t_in_2();
    test_mem_device_wchar_t_in_3();
    test_mem_device_wchar_t_out_1();
    test_mem_device_wchar_t_out_2();
    test_mem_device_wchar_t_out_3();
    test_mem_device_wchar_t_io_1();
    test_mem_device_wchar_t_io_2();
    
    test_mem_device_char32_t_gen_1();
    test_mem_device_char32_t_gen_2();
    test_mem_device_char32_t_gen_3();
    test_mem_device_char32_t_in_1();
    test_mem_device_char32_t_in_2();
    test_mem_device_char32_t_in_3();
    test_mem_device_char32_t_out_1();
    test_mem_device_char32_t_out_2();
    test_mem_device_char32_t_out_3();
    test_mem_device_char32_t_io_1();
    test_mem_device_char32_t_io_2();

    test_mem_device_char8_t_gen_1();
    test_mem_device_char8_t_gen_2();
    test_mem_device_char8_t_gen_3();
    test_mem_device_char8_t_in_1();
    test_mem_device_char8_t_in_2();
    test_mem_device_char8_t_in_3();
    test_mem_device_char8_t_out_1();
    test_mem_device_char8_t_out_2();
    test_mem_device_char8_t_out_3();
    test_mem_device_char8_t_io_1();
    test_mem_device_char8_t_io_2();
    
    test_std_device_gen_1();
    test_std_device_input_1();
    test_std_device_output_1();
    test_std_device_output_2();

    test_file_device_char_gen_1();
    test_file_device_char_close_1();
    test_file_device_char_close_2();
    test_file_device_char_is_open_1();
    test_file_device_char_is_open_2();
    test_file_device_char_get_1();
    test_file_device_char_get_2();
    test_file_device_char_get_3();
    test_file_device_char_seek_1();
    test_file_device_char_seek_2();
    test_file_device_char_seek_3();
    test_file_device_char_seek_4();
    test_file_device_char_seek_5();
    test_file_device_char_seek_6();
    test_file_device_char_seek_7();
    test_file_device_char_seek_8();

    test_file_device_char8_t_gen_1();
    test_file_device_char8_t_close_1();
    test_file_device_char8_t_close_2();
    test_file_device_char8_t_is_open_1();
    test_file_device_char8_t_is_open_2();
    test_file_device_char8_t_get_1();
    test_file_device_char8_t_get_2();
    test_file_device_char8_t_get_3();
    test_file_device_char8_t_seek_1();
    test_file_device_char8_t_seek_2();
    test_file_device_char8_t_seek_3();
    test_file_device_char8_t_seek_4();
    test_file_device_char8_t_seek_5();
    test_file_device_char8_t_seek_6();
    test_file_device_char8_t_seek_7();
    test_file_device_char8_t_seek_8();
}